#######################################
### RabbitMQ Service
###
#######################################
rabbitmq:
  image: rabbitmq:4-management
  #    build:
  #      context: build
  #      dockerfile: rabbit-stomp.Dockerfile
  ports:
    - '15672:15672'
    #      - '15674:15674'
    - '5672:5672'
  healthcheck:
    test: rabbitmq-diagnostics -q ping
    interval: 8s
    timeout: 30s
    retries: 3
  networks:
    - toubilib.net
  volumes:
    - ./rabbitmq.toubi:/var/lib/rabbitmq
  environment:
    - RABBITMQ_DEFAULT_USER: toubi
    - RABBITMQ_DEFAULT_PASS: toubi

#################################################
#
# Ajouter dans les services qui utilisent le serveur rabbitmq :
#      depends_on:
#        rabbitmq:
#           condition: service_healthy

##############################################
###
###  MailCatcher
###############################################
mail.toubi:
  build:
    context: build
    dockerfile: mailcatcher.Dockerfile
  networks:
    - toubilib.net
  ports:
    - '1080:1080'

